POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "teste1",
    "email": "teste2email.com",
    "password": "23432535"
}

###

GET http://localhost:3003/user/get

###

POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "title": "Cenicienta",
    "description": "Historia de una pueblerina",
    "durationInMinutes": 160,
    "yearOfRelease":1990
}
