POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "teste2",
    "email": "teste2@email.com",
    "password": "23432535"
}

###

GET http://localhost:3003/user/get

###

POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "title": "El lago de los cisnes",
    "description": "Historia de una bailarina",
    "duration_in_minutes": 160,
    "year_of_release":2017
}
